[package]
name = "hypervisor-agent"
version = "0.1.0"
authors = ["Jean-Baptiste Kaiser <kaiserjean@eisti.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
